### ISSUE TITLE
Seems not working

### ISSUE THREAD

**Issue by rayit** [lotherk/platformio-openbsd-toolchain-xtensa#1]
` 
/home/rayit/.local/bin/pio run      
Processing nodemcuv2 (platform: espressif8266; framework: arduino; board: nodemcuv2)
---------------------------------------------------------------------
Tool Manager: Installing platformio/toolchain-xtensa @ ~2.40802.0
Error: Could not find the package with 'platformio/toolchain-xtensa @ ~2.40802.0' requirements for your system 'openbsd_amd64'
`

I followed manual on Reddit
https://www.reddit.com/r/openbsd/comments/jlz79z/esp8266_development_on_openbsd_with_platformio/

But seems not working.
Do you have advice.

Thanks
Rayit

**Comment by sralmai** [comment]
Hi @rayit . https://github.com/lotherk/platformio-openbsd-toolchain-xtensa/pull/2 should solve your problem.

**Comment by rayit** [comment]
Thanks!!
